
name: Run Project Tests

on: 
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.1'
    
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --without development test

    - name: Run tests
      run: |
        RAILS_ENV=test bundle exec rails test
